services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    networks:
      network_service:
        ipv4_address: 10.10.3.51 # 9000 & 9090
    volumes:
      - data:/data

networks:
  network_service:
    external: true

volumes:
  data:
    external: false